{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww20880\viewh12860\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 /*Number of Distinct Campaigns*/\
SELECT COUNT(DISTINCT utm_campaign) AS 'Number of Campaigns' \
FROM page_visits;\
\
/*Number of Distinct Sources */\
SELECT COUNT(DISTINCT utm_source) AS 'Number of Sources' FROM page_visits;\
\
/*Relation between Sources and Campaigns */\
SELECT DISTINCT utm_campaign AS 'Campaign', \
			utm_source as 'Source' \
FROM page_visits;\
\
/* Pages on CoolTShirts Website */\
SELECT DISTINCT page_name AS 'Page' \
FROM page_visits;\
\
/*First Touches generated by each Campaign*/\
WITH first_touch AS (\
    SELECT user_id,\
        MIN(timestamp) AS first_touch_at\
    FROM page_visits\
    GROUP BY user_id)\
SELECT \
  	pv.utm_source AS 'Source',\
		pv.utm_campaign AS 'Campaign',\
    COUNT(*) AS 'Number of First Touches'\
FROM first_touch ft\
	JOIN page_visits pv\
	ON ft.user_id = pv.user_id\
	AND ft.first_touch_at = pv.timestamp\
  GROUP BY 1,2\
  ORDER BY 3 DESC;\
\
/*Last Touches generated by each Campaign*/\
WITH last_touch AS (\
    SELECT user_id,\
       MAX(timestamp) AS 'last_touch_at'\
    FROM page_visits\
    GROUP BY user_id)\
SELECT \
  	pv.utm_source AS 'Source',\
		pv.utm_campaign AS 'Campaign',\
    COUNT(*) AS 'Number of Last Touches'\
FROM last_touch lt\
	JOIN page_visits pv\
	ON lt.user_id = pv.user_id\
	AND lt.last_touch_at = pv.timestamp\
  GROUP BY 1,2\
  ORDER BY 3 DESC;\
\
/* No of Visitors who make a purchase */\
SELECT COUNT (DISTINCT user_id) AS 'No of Visitors who made a Purchase'\
 FROM page_visits \
 WHERE page_name = '4 - purchase';\
\
/*Last touches each campaign is responsible for */\
WITH last_touch AS (\
    SELECT user_id,\
       MAX(timestamp) AS 'last_touch_at'\
    FROM page_visits\
   WHERE page_name = '4 - purchase'\
    GROUP BY user_id)\
SELECT \
  	pv.utm_source AS 'Source',\
		pv.utm_campaign AS 'Campaign',\
    COUNT(*) AS 'Number of Last Touches'\
FROM last_touch lt\
	JOIN page_visits pv\
	ON lt.user_id = pv.user_id\
	AND lt.last_touch_at = pv.timestamp\
  GROUP BY 1,2\
  ORDER BY 3 DESC;\
}